input_features:
  - name: body
    type: text
    encoder: bert
  - name: time_received
    type: date
    preprocessing:
      datetime_format: "%Y-%m-%d %H:%M:%S"
  - name: sender
    type: category

preprocessing:
  split:
      type: fixed
      column: split
  oversample_minority:
    0.5  # Give each class 50% representation

trainer:
  validation_metric: roc_auc

output_features:
  - name: replied_to
    type: binary
