version: 1

# This ensures loggging works in imported modules, too. The problem is that
# the logging config is loaded *after* modules have been imported, and by
# default loading a logging config from file will disable all loggers that
# already exist. See
# https://fangpenlin.com/posts/2012/08/26/good-logging-practice-in-python/
disable_existing_loggers: false

formatters:
  simple:
    format: '%(levelname)s - %(asctime)8s - %(name)s - %(filename)s, line %(lineno)4s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  mainLogger:
    level: DEBUG
    handlers: [console]
    propagate: yes
root:
  level: DEBUG
  handlers: [console]
